# Generated by Django 4.2.1 on 2023-05-10 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='location',
            field=models.CharField(blank=True, choices=[('Russia, Anadyr - Asia/Anadyr', 'Russia, Anadyr'), ('Russia, Astrakhan - Europe/Astrakhan', 'Russia, Astrakhan'), ('Russia, Barnaul - Asia/Barnaul', 'Russia, Barnaul'), ('Russia, Chita - Asia/Chita', 'Russia, Chita'), ('Russia, Irkutsk - Asia/Irkutsk', 'Russia, Irkutsk'), ('Russia, Kaliningrad - Europe/Kaliningrad', 'Russia, Kaliningrad'), ('Russia, Kamchatka - Asia/Kamchatka', 'Russia, Kamchatka'), ('Russia, Khandyga - Asia/Khandyga', 'Russia, Khandyga'), ('Russia, Kirov - Europe/Kirov', 'Russia, Kirov'), ('Russia, Krasnoyarsk - Asia/Krasnoyarsk', 'Russia, Krasnoyarsk'), ('Russia, Magadan - Asia/Magadan', 'Russia, Magadan'), ('Russia, Moscow - Europe/Moscow', 'Russia, Moscow'), ('Russia, Novokuznetsk - Asia/Novokuznetsk', 'Russia, Novokuznetsk'), ('Russia, Novosibirsk - Asia/Novosibirsk', 'Russia, Novosibirsk'), ('Russia, Omsk - Asia/Omsk', 'Russia, Omsk'), ('Russia, Sakhalin - Asia/Sakhalin', 'Russia, Sakhalin'), ('Russia, Samara - Europe/Samara', 'Russia, Samara'), ('Russia, Saratov - Europe/Saratov', 'Russia, Saratov'), ('Russia, Srednekolymsk - Asia/Srednekolymsk', 'Russia, Srednekolymsk'), ('Russia, Tomsk - Asia/Tomsk', 'Russia, Tomsk'), ('Russia, Ulyanovsk - Europe/Ulyanovsk', 'Russia, Ulyanovsk'), ('Russia, Ust-Nera - Asia/Ust-Nera', 'Russia, Ust-Nera'), ('Russia, Vladivostok - Asia/Vladivostok', 'Russia, Vladivostok'), ('Russia, Volgograd - Europe/Volgograd', 'Russia, Volgograd'), ('Russia, Yakutsk - Asia/Yakutsk', 'Russia, Yakutsk'), ('Russia, Yekaterinburg - Asia/Yekaterinburg', 'Russia, Yekaterinburg')], max_length=128, null=True, verbose_name='location'),
        ),
        migrations.AlterField(
            model_name='client',
            name='tag',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='tag'),
        ),
    ]
