# Generated by Django 4.2.1 on 2023-05-11 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_client_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='mobile_code',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='mobile_code'),
        ),
    ]
