# Generated by Django 4.2.1 on 2023-05-10 20:51

from django.db import migrations, models
import django.db.models.deletion
import main.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=16, unique=True, validators=[main.validators.validate_phone], verbose_name='phone')),
                ('tag', models.CharField(max_length=64, verbose_name='tag')),
                ('location', models.CharField(choices=[('Russia, Anadyr - Asia/Anadyr', 'Russia, Anadyr'), ('Russia, Astrakhan - Europe/Astrakhan', 'Russia, Astrakhan'), ('Russia, Barnaul - Asia/Barnaul', 'Russia, Barnaul'), ('Russia, Chita - Asia/Chita', 'Russia, Chita'), ('Russia, Irkutsk - Asia/Irkutsk', 'Russia, Irkutsk'), ('Russia, Kaliningrad - Europe/Kaliningrad', 'Russia, Kaliningrad'), ('Russia, Kamchatka - Asia/Kamchatka', 'Russia, Kamchatka'), ('Russia, Khandyga - Asia/Khandyga', 'Russia, Khandyga'), ('Russia, Kirov - Europe/Kirov', 'Russia, Kirov'), ('Russia, Krasnoyarsk - Asia/Krasnoyarsk', 'Russia, Krasnoyarsk'), ('Russia, Magadan - Asia/Magadan', 'Russia, Magadan'), ('Russia, Moscow - Europe/Moscow', 'Russia, Moscow'), ('Russia, Novokuznetsk - Asia/Novokuznetsk', 'Russia, Novokuznetsk'), ('Russia, Novosibirsk - Asia/Novosibirsk', 'Russia, Novosibirsk'), ('Russia, Omsk - Asia/Omsk', 'Russia, Omsk'), ('Russia, Sakhalin - Asia/Sakhalin', 'Russia, Sakhalin'), ('Russia, Samara - Europe/Samara', 'Russia, Samara'), ('Russia, Saratov - Europe/Saratov', 'Russia, Saratov'), ('Russia, Srednekolymsk - Asia/Srednekolymsk', 'Russia, Srednekolymsk'), ('Russia, Tomsk - Asia/Tomsk', 'Russia, Tomsk'), ('Russia, Ulyanovsk - Europe/Ulyanovsk', 'Russia, Ulyanovsk'), ('Russia, Ust-Nera - Asia/Ust-Nera', 'Russia, Ust-Nera'), ('Russia, Vladivostok - Asia/Vladivostok', 'Russia, Vladivostok'), ('Russia, Volgograd - Europe/Volgograd', 'Russia, Volgograd'), ('Russia, Yakutsk - Asia/Yakutsk', 'Russia, Yakutsk'), ('Russia, Yekaterinburg - Asia/Yekaterinburg', 'Russia, Yekaterinburg')], max_length=128, verbose_name='location')),
            ],
            options={
                'verbose_name': 'client',
                'verbose_name_plural': 'clients',
            },
        ),
        migrations.CreateModel(
            name='CodeMobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_mobile', models.CharField(max_length=3, unique=True, verbose_name='code mobile')),
            ],
            options={
                'verbose_name': 'code mobile',
                'verbose_name_plural': 'codes mobile',
            },
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='message')),
                ('start', models.DateTimeField(verbose_name='start date time')),
                ('stop', models.DateTimeField(verbose_name='stop date time')),
                ('mobile_codes', models.ManyToManyField(blank=True, related_name='mailing_codes', to='main.codemobile', verbose_name='codes')),
            ],
            options={
                'verbose_name': 'mailing',
                'verbose_name_plural': 'mailings',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=64, unique=True, verbose_name='tag')),
            ],
            options={
                'verbose_name': 'tag',
                'verbose_name_plural': 'tags',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('send', models.BooleanField(default=False, verbose_name='send message')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='msg_client', to='main.client', verbose_name='client')),
                ('mailing', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='msg_mailing', to='main.mailing', verbose_name='mailing')),
            ],
            options={
                'verbose_name': 'message',
                'verbose_name_plural': 'messages',
            },
        ),
        migrations.AddField(
            model_name='mailing',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='mailing_tags', to='main.tag', verbose_name='tags'),
        ),
    ]
