# Generated by Django 4.2.1 on 2023-05-10 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeMobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_mobile', models.CharField(max_length=3, unique=True, verbose_name='code mobile')),
            ],
            options={
                'verbose_name': 'code mobile',
                'verbose_name_plural': 'codes mobile',
            },
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='message')),
                ('start', models.DateTimeField(verbose_name='start date time')),
                ('stop', models.DateTimeField(verbose_name='stop date time')),
                ('mobile_codes', models.ManyToManyField(blank=True, related_name='mailing_codes', to='main.codemobile', verbose_name='codes')),
            ],
            options={
                'verbose_name': 'mailing',
                'verbose_name_plural': 'mailings',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=64, unique=True, verbose_name='tag')),
            ],
            options={
                'verbose_name': 'tag',
                'verbose_name_plural': 'tags',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('send', models.BooleanField(default=False, verbose_name='send message')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='msg_client', to='client.client', verbose_name='client')),
                ('mailing', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='msg_mailing', to='main.mailing', verbose_name='mailing')),
            ],
            options={
                'verbose_name': 'message',
                'verbose_name_plural': 'messages',
            },
        ),
        migrations.AddField(
            model_name='mailing',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='mailing_tags', to='main.tag', verbose_name='tags'),
        ),
    ]
